name: 'Validate Integration JSON'
description: 'Validate an integration configuration JSON according to the schema defined in [@leanix/nexus](https://github.com/leanix/nexus)'
author: 'LeanIX'
inputs:
  integration-json:
    required: true
    description: 'Absolute path to the integration JSON file'
runs:
  using: 'node16'
  main: 'dist/index.js'
