name: Generate integrations client model

on:
  repository_dispatch:
    types: [openapi-spec-updated]

jobs:
  generate-openapi-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Write spec to file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ runner.temp }}/${{ github.event.client_payload.name }}.json
          contents: ${{ toJSON(github.event.client_payload.spec) }}

      - name: Generate client
        run: npx ng-openapi-gen -i ${{ runner.temp }}/${{ github.event.client_payload.name }}.json -o ${{ runner.temp }}/.openapi-generated/${{ github.event.client_payload.name }} --ignoreUnusedModels false --indexFile true --skipJsonSuffix true --module false --modelIndex false --serviceIndex false

      - name: Copy generated files to destination folder
        run: npx ts-node ./scripts/copy-generated-openapi-files.ts -- ${{ github.event.client_payload.name }} ${{ runner.temp }}/.openapi-generated/${{ github.event.client_payload.name }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: openapi-${{ github.event.client_payload.sha }}
          base: ${{ github.event.repository.default_branch }}
          title: Update OpenAPI client files for ${{ github.event.client_payload.name }}
          author: leanix-ci <leanix-ci@users.noreply.github.com>
          commit-message: Update OpenAPI client files for ${{ github.event.client_payload.name }}
          body: This PR has been created automatically to reflect the backend changes of ${{ github.event.client_payload.name }}
