name: 'build & test'
on: # rebuild any PRs and main branch changes
  push:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'dist/**'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Inject secret store credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
          token: ${{ env.GITHUB_TOKEN }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies & build
        run: |
          npm install
          npm run all

      - name: Commit & push dist folder if needed
        run: |
          if expr $(git status --porcelain | grep dist | wc -l) \> 0; then
            git config user.name leanix-ci
            git config user.email 'leanix-ci@users.noreply.github.com'
            git add dist
            git commit -m "Update dist files"
            git push
          else
            echo "No dist files were updated"
          fi

  # make sure the action works on a clean machine without building
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Inject secret store credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: |
          INTEGRATION_JSON=$(echo "$(pwd)/test/testdata/integration-test.json")
          echo "integration_json="$INTEGRATION_JSON >> $GITHUB_ENV
      - uses: ./
        with:
          integration-json: '${{ env.integration_json }}'
          # skip-post-integration: 'true'
