name: PR Notification
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-default-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
