name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: |
          npm install
          npm run all

  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          INTEGRATION_JSON=$(echo "$(pwd)/test/testdata/integration-test.json")
          echo "integration_json="$INTEGRATION_JSON >> $GITHUB_ENV
      - uses: ./
        with:
          integration-id: 'test'
          integration-json: '${{ env.integration_json }}'
